[package]
name = "beercanlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", features = ["sqlite"] }
mio = { version = "0.8.5", features = ["net", "os-poll"] }
rand = "0.8.5"
rustls = "0.20.8"
